environment:
  python_version: "3.11"
  device_preference: "mps"

paths:
  checkpoints: "storage/checkpoints/ada_core.pt"
  conversations_db: "storage/conversations.db"

cli:
  persona: "core/persona.yaml"
  greeting: "Hello Taahirah, neural core initialized and ready to learn."

voice:
  stt_backend: "whispercpp"
  stt_binary: "/Volumes/My Passport for Mac/Ada/whisper.cpp/main"
  stt_model: "/Volumes/My Passport for Mac/Ada/whisper.cpp/models/ggml-base.en.bin"
  tts_backend: "piper"
  tts_binary: "./bin/piper"
  tts_voice: "voices/en_US-amy-low.onnx"
  vad: "silero"
  persona_voice: "female_warm"

reinforcement:
  voice_reward: true
  reward_scale: 0.5

memory:
  episodic_enabled: true
  db_path: "storage/conversations.db"
  recall_top_k: 3
  min_similarity: 0.1
  max_context_tokens: 100
  cleanup_old_days: 30

persona:
  enabled: true
  update_interval: 20 # dialogs
  drift_threshold: 0.3
  bias_weight: 0.2

planner:
  enabled: true
  auto_infer: true
  max_concurrent_plans: 3
  tools:
    allow_local: ["file_ops","summarize","note"]
    confirm_before_write: true

missions:
  enabled: true
  check_interval_minutes: 60
  curriculum_learning: true
  auto_audit: true
