environment:
  python_version: "3.11"
  device_preference: "mps"

paths:
  checkpoints: "storage/checkpoints/ada_core.pt"
  conversations_db: "storage/conversations.db"

cli:
  persona: "core/persona.yaml"
  greeting: "Hello Taahirah, neural core initialized and ready to learn."

voice:
  stt_backend: "whispercpp"
  stt_binary: "/Volumes/My Passport for Mac/Ada/whisper.cpp/main"
  stt_model: "/Volumes/My Passport for Mac/Ada/whisper.cpp/models/ggml-base.en.bin"
  tts_backend: "piper"
  tts_binary: "./bin/piper"
  tts_voice: "voices/en_US-amy-low.onnx"
  vad: "silero"
  persona_voice: "female_warm"

reinforcement:
  voice_reward: true
  reward_scale: 0.5

memory:
  episodic_enabled: true
  db_path: "storage/conversations.db"
  recall_top_k: 3
  min_similarity: 0.1
  max_context_tokens: 100
  cleanup_old_days: 30

persona:
  enabled: true
  update_interval: 20 # dialogs
  drift_threshold: 0.3
  bias_weight: 0.2

planner:
  enabled: true
  auto_infer: true
  max_concurrent_plans: 3
  tools:
    allow_local: ["file_ops","summarize","note"]
    confirm_before_write: true

missions:
  enabled: true
  check_interval_minutes: 60
  curriculum_learning: true
  auto_audit: true

optimizer:
  enabled: true
  evaluation_interval_hours: 6
  max_population: 5
  mutation_rate: 0.15
  selection_top_k: 2
  preserve_best: true
  rollback_safe: true

cloud:
  enabled: true
  provider: "modal"
  endpoint: "https://ada-cloud.modal.run"
  api_key: "${ADA_API_KEY}"
  gpu_enabled: true
  auto_scale_zero: true
  timeout: 300
  max_retries: 3
  enable_streaming: true

storage:
  provider: "wasabi"
  endpoint: "https://s3.wasabisys.com"
  region: "us-east-1"
  bucket: "ada-models"
  access_key_id: "${WASABI_KEY_ID}"
  secret_access_key: "${WASABI_SECRET}"
  min_storage_days: 90
  sync_on_startup: true
  compression: true

adaptive:
  enabled: true
  reinforcement:
    learning_rate: 0.0005
    immediate_update: true
    min_reward_threshold: 0.1
  memory:
    enabled: true
    model_name: "all-MiniLM-L6-v2"
    recall_top_k: 3
    max_memories: 10000
    storage_path: "storage/memory"
  optimizer:
    schedule: "weekly"
    gpu_type: "A10G"
    min_feedback_entries: 10
    batch_size: 8
  logging:
    path: "logs/training_feedback.jsonl"
    auto_rotate: true
    max_file_size_mb: 100
